In [1]:
import numpy as np

In [2]:
arr = np.array([12, 24, 56, 78, 100])

In [3]:
arr

array([ 12,  24,  56,  78, 100])

In [47]:
arr1 = np.array([12, 33.44, "Raj",True, ])

In [49]:
arr1

array(['12', '33.44', 'Raj', 'True'], dtype='<U32')

In [51]:
arr1.dtype

dtype('<U32')

In [53]:
type(arr1)

numpy.ndarray

In [55]:
arr1[1]

'33.44'

In [57]:
arr1[1] = 100

In [59]:
arr1

array(['12', '100', 'Raj', 'True'], dtype='<U32')

In [61]:
import time

In [63]:
time.time()

1744877809.9582143

In [65]:
values = 1000000

l1 = list(range(values))

arr = np.array(l1)

In [67]:
start_time = time.time()
newl = [i * 2 for i in l1]
required_time = time.time() - start_time
print(f"time for list -> {required_time}")

time for list -> 0.025986909866333008


In [69]:
start_time = time.time()
newarr = arr * 2
required_time1 = time.time() - start_time
print(f"time for array -> {required_time}")

time for array -> 0.025986909866333008


In [71]:
required_time/ required_time1 

8.023925206124852

In [73]:
# arange

In [75]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
np.arange(5, 101, 5.5)

array([ 5. , 10.5, 16. , 21.5, 27. , 32.5, 38. , 43.5, 49. , 54.5, 60. ,
       65.5, 71. , 76.5, 82. , 87.5, 93. , 98.5])

In [79]:
np.arange(-5, 5, 0.5)

array([-5. , -4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,
        0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [81]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [83]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [85]:
r1 = np.array([12, 34, 5, 7, 10])

In [87]:
r1

array([12, 34,  5,  7, 10])

In [89]:
r1[1: 4]

array([34,  5,  7])

In [91]:
r1.size

5

In [93]:
r1.ndim

1

In [95]:
r1.shape

(5,)

In [97]:
# 2d arrays

In [99]:
arr = np.array([[1, 2, 3], [4, 5, 6], [12, 13, 10], [1, 5, 2]])

In [101]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [12, 13, 10],
       [ 1,  5,  2]])

In [103]:
arr.ndim

2

In [105]:
arr.shape

(4, 3)

In [107]:
arr.size

12

In [109]:
arr.flatten()

array([ 1,  2,  3,  4,  5,  6, 12, 13, 10,  1,  5,  2])

In [111]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [12, 13, 10],
       [ 1,  5,  2]])

In [113]:
arr[1:, 1:]

array([[ 5,  6],
       [13, 10],
       [ 5,  2]])

In [115]:
arr[3, 2]

2

In [117]:
arr[1:3, [0, 2]]

array([[ 4,  6],
       [12, 10]])

In [119]:
#

In [121]:
for i in range(1, 5):
    print(i)

1
2
3
4


In [123]:
for i in range(1, 5):
    if i == 3:
        continue
    print(i)

1
2
4


In [125]:
for i in range(1, 5):
    pass

In [127]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [12, 13, 10],
       [ 1,  5,  2]])

In [130]:
arr.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6, 12, 13],
       [10,  1,  5,  2]])

In [132]:
arr.reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [12, 13, 10,  1,  5,  2]])

In [134]:
arr.reshape(2, -1)

array([[ 1,  2,  3,  4,  5,  6],
       [12, 13, 10,  1,  5,  2]])

In [136]:
arr.reshape(3, 2, 2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [12, 13]],

       [[10,  1],
        [ 5,  2]]])

In [138]:
arr.reshape(3, 2, 2).ndim

3

In [140]:
arr.reshape(3, 2, -1)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [12, 13]],

       [[10,  1],
        [ 5,  2]]])

In [142]:
arr.reshape(4, 3, -1)

array([[[ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6]],

       [[12],
        [13],
        [10]],

       [[ 1],
        [ 5],
        [ 2]]])

In [144]:
arr1 = np.array([[1, 2, 3], [4, 5, 6], [12, 13, 10]])
arr2 = np.array([[1, 10, 3], [4, 15, 5], [10, 13, 10]])

In [146]:
arr1 @ arr2

array([[ 39,  79,  43],
       [ 84, 193,  97],
       [164, 445, 201]])

In [148]:
np.dot(arr1, arr2)

array([[ 39,  79,  43],
       [ 84, 193,  97],
       [164, 445, 201]])

In [150]:
np.linalg.det(arr1)

12.0

In [154]:
np.linalg.inv(arr1)

array([[-2.33333333,  1.58333333, -0.25      ],
       [ 2.66666667, -2.16666667,  0.5       ],
       [-0.66666667,  0.91666667, -0.25      ]])

In [156]:
np.linalg.eig(arr1)

EigResult(eigenvalues=array([19.02862769, -0.2249273 , -2.80370039]), eigenvectors=array([[-0.19446948, -0.59857427, -0.42601189],
       [-0.43208577,  0.75749569, -0.40402646],
       [-0.88061542, -0.2605938 ,  0.8094915 ]]))